export { default as Login } from './Login/Login';
export { default as Checkout } from './Customer/Checkout/CheckoutPage';
export { default as Home } from './Home/Home';
export { default as Register } from './Register/Register';
export { default as Customer } from './Customer/Customer';
export { default as Products } from './Customer/Products/Products';
export { default as RequestsSeller } from './Seller/Requests/RequestsSeller';
export { default as Orders } from './Customer/Orders/Orders';
export { default as Manage } from './Admin/Manage/Manage';
